### ISSUE TITLE
Annotation doesn't show after clicking on a second span link

### ISSUE THREAD

**Issue by hcgriggs** [scholarslab/nl-widget-Text#5]
Hi,
I've installed up Neatline text as well as NeatlineSIMILE for a class project. When I first click on spanned link, it works fine; however, when I click on a second, it just zooms in to the location and does not display the annotation. I don't know how to resolve this issue---how can I make the second annotation display correctly, as well as subsequent annotations? 

I have made it public to show the issue: http://forgivemehome.com/omeka/neatline/show/the-cradle-of-civilized-drinking

Thank you!

**Comment by davidmcclure** [comment]
Hey @hcgriggs,

This is actually a bug in the core Neatline plugin, which was fixed a couple weeks ago. There hasn't been an official release since then, but you can get the new code by downloading the `develop` branch:

https://github.com/scholarslab/Neatline/archive/develop.zip

Let me know if this fixes it. @erochest, maybe we should cut off a 2.5.1 release?

**Comment by erochest** [comment]
Agreed. Unfortunately I'm slammed this week, but I'll put it on my calendar to do a release early next week.

**Comment by hcgriggs** [comment]
Hi @davidmcclure,

I deleted the plugin and then reinstalled the new version of Neatline, and it seems to be working fine now! Thank you so much!

**Comment by davidmcclure** [comment]
Great.
